# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Minor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Minor(object):
    def setupUi(self, Minor):
        Minor.setObjectName("Minor")
        Minor.resize(1232, 826)
        self.centralwidget = QtWidgets.QWidget(Minor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1231, 831))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bk.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(380, 760, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setAutoFillBackground(False)
        self.Start.setStyleSheet("background-color:rgb(67, 203, 0);\n"
"")
        self.Start.setCheckable(False)
        self.Start.setObjectName("Start")
        self.Start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Start_2.setGeometry(QtCore.QRect(720, 750, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Start_2.setFont(font)
        self.Start_2.setAutoFillBackground(False)
        self.Start_2.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.Start_2.setCheckable(False)
        self.Start_2.setObjectName("Start_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(440, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius: none;\n"
"color:white; \n"
"font-size: 20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(630, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius: none;\n"
"color:white; \n"
"font-size: 20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 610, 271, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("initiate system.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        Minor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Minor)
        QtCore.QMetaObject.connectSlotsByName(Minor)

    def retranslateUi(self, Minor):
        _translate = QtCore.QCoreApplication.translate
        Minor.setWindowTitle(_translate("Minor", "MainWindow"))
        self.Start.setText(_translate("Minor", "Start"))
        self.Start_2.setText(_translate("Minor", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Minor = QtWidgets.QMainWindow()
    ui = Ui_Minor()
    ui.setupUi(Minor)
    Minor.show()
    sys.exit(app.exec_())


